#!/usr/bin/env node

const axios = require('axios')
const _csvStringify = require('csv-stringify')
const { promisify } = require('util')

const csvStringify = promisify(_csvStringify.stringify)

async function action({ from, to, baseUrl }) {
  const result = await axios.get(`${baseUrl}/trackingReport`, { params: { from, to } })
  console.log(await csvStringify(result.data.report, { header: true }))
}

module.exports = {
  action,
}
